editor = "code"
auto_update = true
plugin_dirs = ["plugins"]

[save]
ask_on_mixed_staging = false

[tui]
font_size = 14
color_theme = "SageDark"
line_numbers = true

[tui.extras]

[ai]
model = "gpt-oss:20b"
api_url = "http://localhost:11434/v1/"
api_key = "ollama"
max_tokens = 4096

[ai.extras]

[pull_requests]
enabled = false
default_base = "main"
provider = "github"
access_token = ""

[pull_requests.extras]

[extras]
